services:
  # FastAPI application
  api:
    image: redbear-mem-open:latest
    container_name: api
    ports:
      - "8002:8000"
    env_file:
      - .env
    environment:
      - SERVER_IP=0.0.0.0
      # 如果代码里必须要 MCP_SERVER_URL，可以先注释或指向占位
      # - MCP_SERVER_URL=
    volumes:
      - ./files:/files
      - /etc/localtime:/etc/localtime:ro
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload --log-level debug
    restart: unless-stopped
    networks:
      - default
      - celery

  # Celery worker
  worker:
    image: redbear-mem-open:latest
    container_name: worker
    env_file:
      - .env
    environment:
      # - MCP_SERVER_URL=
    volumes:
      - ./files:/files
      - /etc/localtime:/etc/localtime:ro
    command: celery -A app.celery_worker.celery_app worker --loglevel=info
    restart: unless-stopped
    networks:
      - celery

networks:
  celery:
